# 工作流名称
name: Create Release and Upload Package

# 触发条件：当一个以 'v' 开头的标签被推送到仓库时
on:
  push:
    tags:
      - 'v*'

# 权限设置：需要写入内容的权限来创建 Release 和提交版本变更
permissions:
  contents: write

jobs:
  build-and-release:
    # 使用最新的 Ubuntu 虚拟机运行
    runs-on: ubuntu-latest
    steps:
      # 第一步：检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第二步：设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      # 第三步：安装项目依赖 (Lerna 也会被安装)
      - name: Install dependencies
        run: npm install

      # 第四步：【新方案】使用 Lerna 更新所有包的版本
      - name: Update package versions with Lerna
        run: |
          # 提取版本号
          VERSION=$(echo ${GITHUB_REF#refs/tags/v})
          # 使用 lerna version 命令，它会智能地更新所有 package.json 和 package-lock.json
          # 并且不会因为本地包而报错
          npx lerna version $VERSION --yes --no-git-tag-version --no-push
      
      # 第五步：构建和打包项目
      - name: Build and create package
        run: |
          npm run build
          npm pack --workspaces

      # 第六步：提交版本更新
      # Lerna 已经修改了 package.json 和 package-lock.json，我们只需提交它们
      - name: Commit version update
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(release): set version to ${{ env.VERSION }}"
          file_pattern: "**/package.json **/package-lock.json"

      # 第七步：创建 GitHub Release 并上传安装包
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: "*.tgz"