# 工作流名称
name: Create Release and Upload Package

# 触发条件：当一个以 'v' 开头的标签被推送到仓库时
on:
  push:
    tags:
      - 'v*'

# 权限设置：需要写入内容的权限来创建 Release 和提交版本变更
permissions:
  contents: write

jobs:
  build-and-release:
    # 使用最新的 Ubuntu 虚拟机运行
    runs-on: ubuntu-latest
    steps:
      # 第一步：检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第二步：设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      # 第三步：安装项目依赖
      - name: Install dependencies
        run: npm install

      # 第四步：根据标签更新版本号
      - name: Extract version from tag
        run: |
          # 从 Git 引用 (例如 refs/tags/v1.2.0) 中提取版本号 (1.2.0)
          # 并将其设置为后续步骤可以使用的环境变量
          echo "VERSION=$(echo ${GITHUB_REF#refs/tags/v})" >> $GITHUB_ENV

      # 4.1 使用 npm pkg set 直接更新所有 workspace 的 package.json 文件
      - name: Update package.json versions
        run: npm pkg set version=${{ env.VERSION }} --workspaces

      # 4.2 更新 package-lock.json 文件以同步变更，避免网络请求
      - name: Update package-lock.json
        run: npm install --package-lock-only

      # 第五步：构建和打包项目
      - name: Build and create package
        run: |
          npm run build
          npm pack --workspaces

      # 第六步：提交版本更新
      # 将 package.json 和 package-lock.json 的版本更新提交回仓库
      - name: Commit version update
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(release): set version to ${{ env.VERSION }}"
          file_pattern: "**/package.json **/package-lock.json"

      # 第七步：创建 GitHub Release 并上传安装包
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # 自动根据从上一个标签到当前标签的提交记录生成发布说明
          generate_release_notes: true
          # 找到由 'npm pack' 命令生成的 .tgz 文件并将其作为附件上传
          files: "*.tgz"