# 工作流名称
name: Create Release and Upload Package

# 触发条件：当一个以 'v' 开头的标签被推送到仓库时
on:
  push:
    tags:
      - 'v*' # 匹配 v1.0, v1.2.3, v2.0.0-beta.1 等标签

# 权限设置：需要写入内容的权限来创建 Release 和上传附件
permissions:
  contents: write

jobs:
  build-and-release:
    # 使用最新的 Ubuntu 虚拟机运行
    runs-on: ubuntu-latest
    steps:
      # 第一步：检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第二步：设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # 您可以根据项目需要更改版本
          cache: 'npm'

      # 第三步：安装项目依赖
      - name: Install dependencies
        run: npm install

      # 第四步：执行打包命令
      # 这个命令来自您的 package.json 文件中的 "package" 脚本
      - name: Build and create package
        run: npm run package

      # 第五步：创建 GitHub Release 并上传安装包
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # 自动根据从上一个标签到当前标签的提交记录生成发布说明
          generate_release_notes: true
          # 找到由 'npm pack' 命令生成的 .tgz 文件并将其作为附件上传
          # npm pack --workspace=@gendoc/cli 会在项目根目录生成 tgz 文件
          files: "*.tgz"